name: 'Upload Escrow Asset'
description: 'Uploads an escrow asset to the cfx portal'
author: 'Lukas Leisten'

branding:
  icon: 'upload-cloud'
  color: 'gray-dark'

inputs:
  cookie:
    description: 'Your Forum Account Cookie'
    required: true
  zipPath:
    description: 'The path to the zip file to upload'
    required: true
  assetId:
    description: 'The asset id to re-upload'
    required: true
  chunkSize:
    description: 'The chunk size to split the file into'
    required: true
    default: 2097152

runs:
  using: node20
  main: dist/index.js
