name: Build and Upload HQ/LQ Versions to CFX Portal

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all branches

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Upload to CFX Portal
        uses: ./
        with:
          cookie: ${{ secrets.FORUM_COOKIE }}
          hq: |
            asset_id: "534537"
            asset_name: "koja-shopheist-hq"
            branch: "main"
            escrow_ignore: ['init.lua', 'shared/config.lua', 'shared/utils.lua', 'shared/startheist.lua']
          lq: |
            asset_id: "534538"
            asset_name: "koja-shopheist-lq"
            branch: "low-quality"
            escrow_ignore: ['init.lua', 'shared/config.lua', 'shared/utils.lua', 'shared/startheist.lua']
