name: Build and Upload to CFX Portal

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Upload to CFX Portal
        uses: ./
        with:
          cookie: ${{ secrets.FORUM_COOKIE }}
          escrowed: |
            asset_id: "534535"
            asset_name: "koja-shopheist-escrowed"
            escrow_ignore: ['init.lua', 'shared/config.lua', 'shared/utils.lua', 'shared/startheist.lua']
          openSource: |
            asset_id: "534536"
            asset_name: "koja-shopheist-source"
